using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace BPayPOCns.Views.AdobeDesign
{
    /// <summary>
    /// Interaction logic for samsung_galaxy_s10___1.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class Main : ContentPage
    {
        public Main()
        {
            InitializeComponent();
        }


        private async void OnBtnSometerClicked(object sender, EventArgs e)
        { // Muestra la vista de espera


            // Navega a la siguiente pagina despues de que la carga este completa

            await Navigation.PushAsync(new Client());

        }

    }
}
	